services:
  frontend:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/frontend-${ENV?}:${TAG?}
    build:
      context: ./
      dockerfile: ./images/frontend/Dockerfile
      target: ${ENV?}
    container_name: ${COMPOSE_PROJECT_NAME}_frontend-${ENV}
    hostname: frontend
    networks:
      - frontend
      - proxy
    restart: unless-stopped

networks:
  frontend:
    name: frontend

  proxy:
    name: proxy
    external: true
